add auto close epic when all references issues are closed
cloudaper/epics-action pull request #8
Opened 2021-01-19 00:55 UTC by alicantokdemir

2021-02-04 16:30 UTC, krystof-k requested changes
Awesome work, @alicantokdemir, thank you! Just minor comments, and if you could also update the `README.md`, that would be great.

And also please remove the `package-lock.json` as we are using Yarn here :)

2021-02-04 16:30 UTC, krystof-k commented on action.yml
> +    description: Auto closes epic issue when all referenced issues are closed
```suggestion
    description: Auto close epic when all referenced issues are closed
```

2021-02-04 16:30 UTC, krystof-k commented on action.yml
> +    default: true
I'd rather keep the default to false so that we don't change the current behavior.

```suggestion
    default: false
```

2021-02-04 16:30 UTC, krystof-k commented on package.json
> +    "lint": "eslint index.js --fix"
Please keep the default lint script without fix (to be used for CI later):

```suggestion
    "lint": "eslint index.js",
    "lint:fix": "eslint index.js --fix"
```

2021-02-16 14:42 UTC, alicantokdemir commented
@krystof-k Sure, updated

2021-02-21 19:27 UTC, krystof-k commented
Great! Works fine, merging. Thanks!

2021-02-21 19:27 UTC, krystof-k approved these changes

2021-02-21 19:28 UTC, merged